version: '3.9'
services:
  server:
    build: .
    ports:
      - '5000:5000'
    
  databse:
    image: 'postgres:13.3'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
        - "data:/var/lib/postgresql/data"
    ports:
      - '5432:5432'

volumes:
  data: